// lib/src/completion/flutter_snippets.dart
// Generated from flutter-snippets-master/snippets/dart.json
import 'vscode_snippets.dart';

class FlutterSnippets {
  static const List<VsSnippet> dart = [
    VsSnippet(prefix: 'fstless', description: 'StatelessWidget snippet', body: 'class \${TM_FILENAME_BASE/(.*)/\${1:/pascalcase}/} extends StatelessWidget {\nconst \${TM_FILENAME_BASE/(.*)/\${1:/pascalcase}/}({ Key? key }) : super(key: key);\n\n  @override\n  Widget build(BuildContext context){\n    return \${2:Container}(\${0});\n  }\n}'),
    VsSnippet(prefix: 'fstful', description: 'Insert a StatefulWidget', body: 'class \${TM_FILENAME_BASE/(.*)/\${1:/pascalcase}/} extends StatefulWidget {\n  const \${TM_FILENAME_BASE/(.*)/\${1:/pascalcase}/}({ Key? key }) : super(key: key);\n\n  @override\n  State<\${TM_FILENAME_BASE/(.*)/\${1:/pascalcase}/}> createState() => \${TM_FILENAME_BASE/(.*)/\${1:/pascalcase}/}State();\n}\n\nclass \${TM_FILENAME_BASE/(.*)/\${1:/pascalcase}/}State extends State<\${TM_FILENAME_BASE/(.*)/\${1:/pascalcase}/}> {\n  @override\n  Widget build(BuildContext context) {\n    return Container(\n      \$2\n    );\n  }\n}'),
    VsSnippet(prefix: 'fscaff', description: 'Scaffold widget snippet', body: 'Scaffold(\n  appBar: AppBar(\n    title: \${1:const} Text(\'\${2:Title}\'),\n  ),\n  body: \${3:Container()},\n)\${3:;}'),
    VsSnippet(prefix: 'fedgall', description: 'EdgeInsets widget snippet with named constructor `all`', body: 'EdgeInsets.all(\${1:32.0})\${0}'),
    VsSnippet(prefix: 'ftxt', description: 'Text widget snippet', body: '\${1:const} Text(\'\${2:text}\')\${0}'),
    VsSnippet(prefix: 'dinvar', description: 'Instance variable snippet', body: '\${1:dynamic} \${2:variableName}\${0}'),
    VsSnippet(prefix: 'dprinvar', description: 'Dart Private instance variable snippet', body: '\${1:dynamic} _\${2:variableName};\${0}'),
    VsSnippet(prefix: 'finitlf', description: 'Flutter initState lifecycle method', body: '@override\nvoid initState() {\n  super.initState();\n  \${0}\n}'),
    VsSnippet(prefix: 'dprmt', description: 'Dart private method snippet', body: '\${1:void} _\${2:methodName}(\${3}) \${4}{\n  \${0}\n}'),
    VsSnippet(prefix: 'dopnctor', description: 'Dart optional named parameters constructor snippet', body: '\${1:constructorName}({\${2}});\${0}'),
    VsSnippet(prefix: 'fic', description: 'Flutter Icon widget snippet', body: 'Icon(Icons.\${1:clear})\${0}'),
    VsSnippet(prefix: 'fcont', description: 'Flutter Container widget snippet', body: 'Container(\n  child: \${1:Widget}(\${0}),\n)'),
    VsSnippet(prefix: 'fcent', description: 'Flutter Center widget snippet', body: 'Center(\n  child: \${1:Widget}(\${0}),\n)'),
    VsSnippet(prefix: 'frow', description: 'Flutter Row widget snippet', body: 'Row(\n  children: <Widget>[\${0}],\n)'),
    VsSnippet(prefix: 'fcol', description: 'Flutter Column widget snippet', body: 'Column(\n  children: <Widget>[\${0}],\n)'),
    VsSnippet(prefix: 'fszb', description: 'SizedBox widget with width and height arguments', body: 'SizedBox(width: \${1:0.0}, height: \${2:0.0})\${0}'),
    VsSnippet(prefix: 'fszbw', description: 'SizedBox widget snippet with just width argument', body: 'SizedBox(\n  width: \${1:0.0},\${0}\n)'),
    VsSnippet(prefix: 'fszbh', description: 'SizedBox widget snippet with just height argument', body: 'SizedBox(\n  height: \${1:0.0},\${0}\n)'),
    VsSnippet(prefix: 'fex', description: 'Expand widget snippet', body: 'Expanded(\n  child: \${1:null},\${0}\n)'),
    VsSnippet(prefix: 'fedgonly', description: 'EdgeInsets widget snippet with named constructor `only`', body: 'EdgeInsets.only(\${1})\${0}'),
    VsSnippet(prefix: 'fedgsym', description: 'EdgeInsets widget snippet with named constructor `symmetric`', body: 'EdgeInsets.symmetric(vertical: \${1:8.0}, horizontal: \${2:8.0},)\${0}'),
    VsSnippet(prefix: 'fedgsymv', description: 'EdgeInsets widget snippet with named constructor `symmetric` with only vertical parameter', body: 'EdgeInsets.symmetric(vertical: \${1:8.0},)\${0}'),
    VsSnippet(prefix: 'fedgsymh', description: 'EdgeInsets widget snippet with named constructor `symmetric` with only horizontal parameter', body: 'EdgeInsets.symmetric(horizontal: \${1:8.0},)\${0}'),
    VsSnippet(prefix: 'dlist', description: 'Dart `List` collection snippet', body: 'List<\${1:dynamic}> \${2:listName}\${0}'),
    VsSnippet(prefix: 'dmap', description: 'Dart `Map` collection snippet', body: 'Map<\${1:dynamic}, \${2:dynamic}> \${3:mapName}\${0}'),
    VsSnippet(prefix: 'dset', description: 'Dart `Set` collection snippet', body: 'Set<\${1:dynamic}> \${2:setName}\${0}'),
    VsSnippet(prefix: 'dgetarr', description: 'Dart arrow function getter snippet', body: '\${1:dynamic} get \${2:name} => \${3:returnValue};\${0}'),
    VsSnippet(prefix: 'dimpas', description: 'Dart `import as` snippet', body: 'import \'\${1:packageName}\' as \${2:alias}\${0};'),
    VsSnippet(prefix: 'dimpshow', description: 'Dart `import show` snippet', body: 'import \'\${1:packageName}\' show \${2:member}\${0};'),
    VsSnippet(prefix: 'dimplazy', description: 'Dart `import deffered as` snippet', body: 'import \'\${1:packageName}\' deferred as \${2:alias}\${0};'),
    VsSnippet(prefix: 'dimphide', description: 'Dart `import hide` snippet', body: 'import \'\${1:packageName}\' hide \${2:excludedMember}\${0};'),
    VsSnippet(prefix: 'dexhide', description: 'Dart `export hide` snippet', body: 'export \'\${1:file}\' hide \${2:excludedMember}\${0};'),
    VsSnippet(prefix: 'dexshow', description: 'Dart `export show` snippet', body: 'export \'\${1:file}\' show \${2:member}\${0};'),
    VsSnippet(prefix: 'dmt', description: 'Dart public method snippet', body: '\${1:void} \${2:methodName}(\${3}) \${4}{\n  \${0}\n}'),
    VsSnippet(prefix: 'dconvert', description: 'Dart `convert` lib import snippet', body: 'import \'dart:convert\'\${0};'),
    VsSnippet(prefix: 'dvar', description: 'Dart `var` variable declaration snippet', body: '\${1:var} \${2:variableName}\${0}'),
    VsSnippet(prefix: 'dfinal', description: 'Dart `final` variable declaration snippet', body: 'final \${1:type} \${2:variableName} \${3:= }\${0};'),
    VsSnippet(prefix: 'dconst', description: 'Dart `const` variable declaration snippet', body: 'const \${1:type} \${2:variableName} \${3:= }\${0};'),
    VsSnippet(prefix: 'darr', description: 'Dart public arrow function snippet', body: '\${1:Object} \${2:methodName}(\${3}) \${4}=> \${0};'),
    VsSnippet(prefix: 'dprarr', description: 'Dart private arrow function snippet', body: '\${1:Object} _\${2:methodName}(\${3}) \${4}=> \${0};'),
    VsSnippet(prefix: 'fimpmat', description: 'Add material\'s package import statement', body: 'import \'package:flutter/material.dart\';'),
    VsSnippet(prefix: 'dimpmeta', description: 'Add meta package import statement', body: 'import \'package:meta/meta.dart\';'),
    VsSnippet(prefix: 'fstream', description: 'Flutter StreamBuilder widget snippet', body: 'StreamBuilder<\${1:dynamic}>(        \n  stream: \${2:yourStream},\n  builder: (BuildContext context, AsyncSnapshot<\${1:dynamic}> snapshot) {\n      if (snapshot.hasData) {\n       // TODO: do something with the data\n       return \${3:Container()};\n      } else if (snapshot.hasError) {\n      // TODO: do something with the error\n       return \${4:Text(snapshot.error.toString())};\n      }\n      // TODO: the data is not ready, show a loading indicator\n      return \${5:Center(child: CircularProgressIndicator())};\n   },\n)'),
    VsSnippet(prefix: 'felbtn', description: 'Flutter ElevatedButton snippet', body: 'ElevatedButton(\n  child: const Text(\'\${1:Button label}\'),\n  onPressed: () {},\n)\${0}'),
    VsSnippet(prefix: 'fblocprov', description: 'Flutter bloc provider snippet', body: 'class \${1:Bloc}Provider extends InheritedWidget {\n  final \${2:BlocTypeName} bloc = \${2:BlocTypeName}();\n\n  \${1:Bloc}Provider({Key key, Widget child})\n      : super(key: key, child: child);\n\n  @override\n  bool updateShouldNotify(InheritedWidget oldWidget) => true;\n\n  static \${2:BlocTypeName} of(BuildContext context) {\n    return (context.inheritFromWidgetOfExactType(\${1:Bloc}Provider)\n            as \${1:Bloc}Provider)\n        .bloc;\n  }\n}'),
    VsSnippet(prefix: 'dan', description: 'Dart anonymous function', body: '(\${1}) \${2}{\${0}}'),
    VsSnippet(prefix: 'dcla', description: 'Dart Class snippet', body: 'class \${TM_FILENAME_BASE/(.*)/\${1:/pascalcase}/} {\n\${0}\n}'),
    VsSnippet(prefix: 'dclae', description: 'Dart Class snippet with extends keyword', body: 'class \${TM_FILENAME_BASE/(.*)/\${1:/pascalcase}/} extends \${2} {\n  \${TM_FILENAME_BASE/(.*)/\${1:/pascalcase}/}(\${0}) : super();\n}'),
  ];
}