// lib/src/theme/theme_neon.dart
//
// "Neon Night" — a high-contrast dark theme with glowing neon accents and
// custom scrollbar styling to demonstrate ScrollbarTheme capabilities.
import 'package:flutter/painting.dart';
import 'color_scheme.dart';
import 'editor_theme.dart';

class QuillThemeNeon {
  static EditorTheme build({String fontFamily = 'monospace', double fontSize = 14.0}) =>
      EditorTheme(
        fontFamily: fontFamily,
        fontSize:   fontSize,
        colorScheme: _scheme,
        blockLines: const BlockLineTheme(
          color:            Color(0x4400FFCC),
          activeColor:      Color(0xCC00FFCC),
          style:            BlockLineStyle.dashed,
          colorMode:        BlockLineColorMode.rainbow,
          rainbowColors: [
            Color(0xFF00FFCC),
            Color(0xFFFF00AA),
            Color(0xFF00AAFF),
            Color(0xFFFFFF00),
            Color(0xFFAA00FF),
            Color(0xFFFF6600),
          ],
          dashLength:       6.0,
          dashGap:          3.0,
          width:            1.0,
          inactiveOpacity:  0.5,
        ),
        bracketPair: const BracketPairTheme(
          fillColor:   Color(0x2200FFCC),
          borderColor: Color(0x9900FFCC),
          borderWidth: 1.5,
          radius:      3.0,
        ),
        indentDots: const IndentDotTheme(
          visible: true,
          color:   Color(0x5500FFCC),
          size:    1.5,
        ),
        // ── Custom scrollbar ────────────────────────────────────────────────
        // Slim translucent thumb with a neon cyan border, no track background,
        // and a 3-second auto-hide delay.
        scrollbar: const ScrollbarTheme(
          thickness:       8.0,
          radius:          4.0,
          thumbColor:      Color(0x6600FFCC),
          trackColor:      Color(0x00000000), // fully transparent track
          borderColor:     Color(0xCC00FFCC),
          borderWidth:     1.0,
          showTrack:       false,
          minThumbLength:  24.0,
          autoHideSeconds: 3.0,
        ),
      );

  static const EditorColorScheme _scheme = EditorColorScheme(
    background:               Color(0xFF0D0D14),
    lineNumberBackground:     Color(0xFF0A0A10),
    currentLineBackground:    Color(0xFF1A1A28),
    selectionColor:           Color(0x5500AAFF),
    searchMatchBackground:    Color(0x55FFFF00),
    searchMatchBorder:        Color(0xFFFFFF00),
    snippetActiveBackground:  Color(0x3300FFCC),
    snippetInactiveBackground:Color(0x1A00FFCC),
    textNormal:               Color(0xFFE0E0FF),
    lineNumber:               Color(0xFF3A3A5C),
    lineNumberCurrent:        Color(0xFF00FFCC),
    nonPrintableChar:         Color(0xFF2A2A3C),
    keyword:                  Color(0xFFFF00AA),
    comment:                  Color(0xFF4A4A7A),
    string:                   Color(0xFFFFFF66),
    number:                   Color(0xFFAA00FF),
    operator_:                Color(0xFF00FFCC),
    identifier:               Color(0xFFE0E0FF),
    function_:                Color(0xFF00AAFF),
    type_:                    Color(0xFF00FFCC),
    annotation:               Color(0xFFFF6600),
    literal:                  Color(0xFFAA00FF),
    htmlTag:                  Color(0xFFFF00AA),
    attrName:                 Color(0xFF00AAFF),
    attrValue:                Color(0xFFFFFF66),
    preprocessor:             Color(0xFFFF6600),
    constant:                 Color(0xFFAA00FF),
    namespace:                Color(0xFF00FFCC),
    label:                    Color(0xFFFF00AA),
    punctuation:              Color(0xFF8080B0),
    blockLine:                Color(0xFF1E1E30),
    blockLineActive:          Color(0xFF00FFCC),
    lineDivider:              Color(0xFF1E1E30),
    hardWrapMarker:           Color(0xFF1E1E30),
    stickyScrollDivider:      Color(0xFF1E1E30),
    selectedTextBorder:       Color(0xFF00FFCC),
    currentRowBorder:         Color(0xFF1E1E30),
    cursor:                   Color(0xFF00FFCC),
    selectionHandle:          Color(0xFF00FFCC),
    scrollBarThumb:           Color(0x6600FFCC),
    scrollBarThumbPressed:    Color(0xFF00FFCC),
    scrollBarTrack:           Color(0x00000000),
    bracketPairBorder:        Color(0xFF00FFCC),
    bracketPairFill:          Color(0x2200FFCC),
    activeBlockLineHighlight: Color(0xFF141422),
    highlightedDelimitersFg:          Color(0xFFFFFF00),
    highlightedDelimitersUnderline:   Color(0xFFFFFF00),
    highlightedDelimitersBg:          Color(0x22FFFF00),
    problemError:             Color(0xFFFF0055),
    problemWarning:           Color(0xFFFF6600),
    problemTypo:              Color(0xFF00AAFF),
    diagnosticTooltipBackground: Color(0xFF0A0A10),
    diagnosticTooltipText:    Color(0xFFE0E0FF),
    completionBackground:     Color(0xFF0A0A10),
    completionItemBackground: Color(0xFF0A0A10),
    completionItemSelected:   Color(0xFF1A1A28),
    completionTextPrimary:    Color(0xFFE0E0FF),
    completionTextSecondary:  Color(0xFF4A4A7A),
    completionTextMatched:    Color(0xFF00FFCC),
    completionBorder:         Color(0xFF1E1E30),
    inlayHintForeground:      Color(0xFF4A4A7A),
    inlayHintBackground:      Color(0xFF1A1A28),
    hoverBackground:          Color(0xFF0A0A10),
    hoverBorder:              Color(0xFF00FFCC),
    hoverText:                Color(0xFFE0E0FF),
    signatureBackground:      Color(0xFF0A0A10),
    signatureBorder:          Color(0xFF1E1E30),
    signatureText:            Color(0xFFE0E0FF),
    signatureHighlightedParam:Color(0xFF00FFCC),
    textActionBackground:     Color(0xFF1E1E30),
    textActionIconColor:      Color(0xFFE0E0FF),
  );
}
