// lib/src/theme/theme_light.dart
import 'package:flutter/painting.dart';
import 'color_scheme.dart';
import 'editor_theme.dart';

class QuillThemeLight {
  static EditorTheme build({String fontFamily = 'monospace', double fontSize = 14.0}) =>
      EditorTheme(
        fontFamily: fontFamily, fontSize: fontSize, colorScheme: _scheme,
        blockLines: const BlockLineTheme(color: Color(0x66CCCCCC), activeColor: Color(0xCC0000FF), width: 1.0, curveRadius: 6.0),
        bracketPair: const BracketPairTheme(fillColor: Color(0x1A0000FF), borderColor: Color(0x800000FF),),
        indentDots: const IndentDotTheme(visible: false, color: Color(0x44999999),),
      );

  static const EditorColorScheme _scheme = EditorColorScheme(
    background: Color(0xFFFFFFFF),
    lineNumberBackground: Color(0xFFF5F5F5),
    currentLineBackground: Color(0xFFEFF3FF),
    selectionColor: Color(0x66ADC8FF),
    searchMatchBackground: Color(0x55FFC66D),
    searchMatchBorder: Color(0xFFFFAA00),
    snippetActiveBackground: Color(0x3300BCD4),
    snippetInactiveBackground: Color(0x1500BCD4),
    textNormal: Color(0xFF24292E),
    lineNumber: Color(0xFF8E9BA8),
    lineNumberCurrent: Color(0xFF24292E),
    nonPrintableChar: Color(0xFFCDD1D7),
    keyword: Color(0xFFD73A49),
    comment: Color(0xFF6A737D),
    string: Color(0xFF032F62),
    number: Color(0xFF005CC5),
    operator_: Color(0xFF24292E),
    identifier: Color(0xFF24292E),
    function_: Color(0xFF6F42C1),
    type_: Color(0xFF005CC5),
    annotation: Color(0xFF6F42C1),
    literal: Color(0xFF005CC5),
    htmlTag: Color(0xFF22863A),
    attrName: Color(0xFFB31D28),
    attrValue: Color(0xFF032F62),
    preprocessor: Color(0xFF6F42C1),
    constant: Color(0xFF005CC5),
    namespace: Color(0xFF6F42C1),
    label: Color(0xFFD73A49),
    punctuation: Color(0xFF6A737D),
    blockLine: Color(0xFFE1E4E8),
    blockLineActive: Color(0xFFBCC3CB),
    lineDivider: Color(0xFFE1E4E8),
    hardWrapMarker: Color(0xFFE1E4E8),
    stickyScrollDivider: Color(0xFFE1E4E8),
    selectedTextBorder: Color(0xFF2A6EBB),
    currentRowBorder: Color(0xFFE1E4E8),
    cursor: Color(0xFF0055CC),
    selectionHandle: Color(0xFF2A6EBB),
    scrollBarThumb: Color(0xFFD0D7DE),
    scrollBarThumbPressed: Color(0xFFBCC3CB),
    scrollBarTrack: Color(0xFFF6F8FA),
    bracketPairBorder: Color(0xFF0365D6), bracketPairFill: Color(0x150365D6), activeBlockLineHighlight: Color(0xFFE8F0FD),
    highlightedDelimitersFg: Color(0xFF0550AE),
    highlightedDelimitersUnderline: Color(0xFF0550AE),
    highlightedDelimitersBg: Color(0x220550AE),
    problemError: Color(0xFFD11A2A),
    problemWarning: Color(0xFFBB8A00),
    problemTypo: Color(0xFF2A6EBB),
    diagnosticTooltipBackground: Color(0xFFF6F8FA),
    diagnosticTooltipText: Color(0xFF24292E),
    completionBackground: Color(0xFFFFFFFF),
    completionItemBackground: Color(0xFFFFFFFF),
    completionItemSelected: Color(0xFFDDE8F8),
    completionTextPrimary: Color(0xFF24292E),
    completionTextSecondary: Color(0xFF6A737D),
    completionTextMatched: Color(0xFF0550AE),
    completionBorder: Color(0xFFD0D7DE),
    inlayHintForeground: Color(0xFF8E9BA8),
    inlayHintBackground: Color(0xFFEAECEF),
    hoverBackground: Color(0xFFFFFFFF),
    hoverBorder: Color(0xFFD0D7DE),
    hoverText: Color(0xFF24292E),
    signatureBackground: Color(0xFFFFFFFF),
    signatureBorder: Color(0xFFD0D7DE),
    signatureText: Color(0xFF24292E),
    signatureHighlightedParam: Color(0xFF0550AE),
    textActionBackground: Color(0xFFF6F8FA),
    textActionIconColor: Color(0xFF24292E),
  );
}
